#! /bin/sh

# KeyBinding manager
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
/home/mpc/.config/bspwm/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# BSPWM Rules
bspc rule -a firefox desktop='^1' 
bspc rule -a kitty desktop='^2' follow=on 
bspc rule -a TelegramDesktop desktop='^3' 
bspc rule -a Clementine desktop='^4'
bspc rule -a gnome-clocks desktop='^5'
# DropDown terminal
bspc rule -a Guake sticky=on state=floating hidden=off
bspc rule -a conky sticky=on state=floating border=off lower=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Adding Persian layout
setxkbmap -layout us,ir -option "grp:alt_shift_toggle"
# Wallpaper
 feh --bg-fill /home/mpc/Pictures/Wallpapers/water_lily-wallpaper-5120x2880.jpg

#Picom 
picom -f &

# Change Focus on hover of pointer
bspc config focus_follows_pointer true

/usr/lib/xfce-polkit/xfce-polkit &
